### PR TITLE
Compatibility with Nuxt 1.4

### PR DESCRIPTION
**Pull request by joostdecock**
This PR bundles the work by @cesasol to port this module to the new hooks system, and  the fixes by @apmontgomery for universal and generate mode.

The module now works in all modes with the latest version of Nuxt (v1.4.0).

Note that for `nuxt generate` mode, you need to configure your `baseURL` and `browserBasseURL` to reach the nuxtent API at build time and in production respectively.

An example config could be something like:

```
api: {
  baseURL: 'http://localhost:3000',
  browserBaseURL: 'http://my-production-domain.com'
}
```

### CODE REVIEW

**Comment by joostdecock** [comment]
Help!

**Comment by derevandal** [comment]
@joostdecock please, remove example's folder for test only module.
`Duplicate module name: nuxtent-example`

**Comment by derevandal** [comment]
@joostdecock or let's remake examples ;)

**Comment by joostdecock** [comment]
@derevandal Removed the examples folder, still breaks for the dev tests, and I'm in way over my head

**Comment by apmontgomery** [comment]
this is a problem with the test setup.  Should just need a couple of small changes to make all tests pass.  
- change nuxt dev dependency to latest
- in test/e2e/common/nuxt.config.js: 
     delete the first line importing nuxtent
     in line 13 change the modules line to `modules: ['@@'],`

**Comment by apmontgomery** [comment]
@joostdecock would you like to make those changes to your PR or would you prefer that I submit a different pull request?

**Comment by joostdecock** [comment]
Those changes are required to fix the PR build. So if you want a new PR, you should perhaps bundle the changes in this PR in it. That way, your PR can essentially replace this one.

Alternatively, you could patch this PR. I have no preference, so you do you.

**Comment by alidcastano** [comment]
closing in favor of #151

**Pull request closed without merging**
