### PR TITLE
Hotfix/breadcrumbs dupe keys

### PR DESCRIPTION
**Pull request by derevandal**
@joostdecock you forgot something hehe
#157

### CODE REVIEW

**Comment by joostdecock** [comment]
Ah yes thanks. I fixed that in my fork, but after I switched to a different branch.

I'll happily merge this, but take note that I'm no longer keeping this branch in sync with my work in my fork.

That is, until at some point I'll merge it all upstream again.

**Comment by easherma** [comment]
@joostdecock any particular reason why you forked off your own version instead of contributing back to this one? I like some of the features I see in your fork but am wary about switching back and forth between an 'official' module and yours (no offense, just the way the open source cookie crumbles ;-p )

**Comment by easherma** [comment]
@joostdecock I might be able to, but I'm probably in a similar boat as you! I'd suggest adding this detail to your Readme (and maybe to the upstream one too if they'd welcome it), so it's a little bit more visible how and why the fork exists and what kind of help you need. Might up all our chances of catching some interest. :-)

**Comment by cesasol** [comment]
I'm currently working on merging the fork from @joostdecock and currently using it in some production websites, this work is visible on the development branch.

**Comment by easherma** [comment]
Good to know! Let me know if there's a way I can help; sounds like at least I may be able to help with testing and writing documentation. :-)

**Comment by cesasol** [comment]
Of course, and also if you would like o join the [slack]( https://join.slack.com/t/nuxtent/shared_invite/enQtMjQ1MzI4MzgxNzI5LTcwOTlkYTczNTMzMGU1YjYyYjlkNzNjNDc3MjQ3YTdmMjc0ZThkZjM1ZWY4ZjhiZjc1MDIwYjJmMjAxODlhMzU) or [gitter](https://gitter.im/nuxtent/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link) channels for feedback with the direction for the new release.

**Comment by joostdecock** [comment]
Ok, I've updated the readme (thanks for the suggestion @easherma ) and I'll be in [the Nuxtent chat room on Gitter](https://gitter.im/nuxtent/Lobby) ready to help out.

**Pull request merged**
