### PR TITLE
Add a working sitemap example

### PR DESCRIPTION
**Pull request by CHH**
Hi, I've tried the sitemap example and it didn't work. I've added a new example here, which I tested locally with multiple content types.

### CODE REVIEW

**Comment by alidcastano** [comment]
This is awesome, thank you for fixing the example!

**Comment by alidcastano** [comment]
@CHH If you ever have questions while your working on nuxtent feel free to ask them in our slack channel https://nuxtent.slack.com/join/shared_invite/enQtMjQ1MzI4MzgxNzI5LTcwOTlkYTczNTMzMGU1YjYyYjlkNzNjNDc3MjQ3YTdmMjc0ZThkZjM1ZWY4ZjhiZjc1MDIwYjJmMjAxODlhMzU

**Comment by CHH** [comment]
@alidcastano did you have any luck getting the sitemap to work with `nuxt generate`? I'm always getting an `Error: connect ECONNREFUSED 127.0.0.1:3000`

**Comment by CHH** [comment]
@alidcastano thanks for the invite!

**Comment by alidcastano** [comment]
I don't use a sitemap currently in my site and don't have a chance to look into it rn but if you open up an issue we can look into it at later time

**Pull request merged**
