### PR TITLE
Switched from path.join to url-join for joining urls

### PR DESCRIPTION
**Pull request by peXed**
This commit fixes issues on Windows and other operating systems.

It replaces nodes path.join to url-join in requestContent.

For more information see:
https://github.com/nuxt-community/nuxtent-module/issues/165
and
https://stackoverflow.com/questions/16301503/can-i-use-requirepath-join-to-safely-concatenate-urls

### CODE REVIEW

**Comment by derevandal** [comment]
I clone your repo and test it (as syslink) with nuxtent-template.

I got this error:
```ps

 DONE  Compiled successfully in -7661ms                                           17:02:51


 OPEN  http://localhost:3000

  nuxt:render Rendering url / +0ms
  nuxt:render Data fetching /: 1ms +0ms
  nuxt:render Rendering url /hello-world +14s
{ Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 80,
  config:
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers:
      { Accept: 'application/json, text/plain, */*',
        connection: 'keep-alive',
        'save-data': 'on',
        'upgrade-insecure-requests': '1',
        'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36',
        dnt: '1',
        referer: 'http://localhost:3000/',
        'accept-encoding': 'gzip, deflate, br',
        'accept-language': 'pt-BR,pt;q=0.9,en-XA;q=0.8,en;q=0.7,en-US;q=0.6' },
     method: 'get',
     baseURL: 'http://localhost:3000/content-api',
     url: '//hello-world?',
     data: undefined },
  request:
   Writable {
     _writableState:
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        destroyed: false,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: true,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: false,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: true,
     _events:
      { response: [Function: handleResponse],
        error: [Function: handleRequestError] },
     _eventsCount: 2,
     _maxListeners: undefined,
     _options:
      { protocol: 'http:',
        maxRedirects: 21,
        maxBodyLength: 10485760,
        path: '//hello-world?',
        method: 'get',
        headers: [Object],
        agent: undefined,
        auth: undefined,
        hostname: null,
        port: null,
        nativeProtocols: [Object],
        pathname: '//hello-world',
        search: '?' },
     _redirectCount: 0,
     _requestBodyLength: 0,
     _requestBodyBuffers: [],
     _onNativeResponse: [Function],
     _currentRequest:
      ClientRequest {
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Socket],
        connection: [Socket],
        _header: 'GET //hello-world? HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nconnection: keep-alive\r\nsave-data: on\r\nupgrade-insecure-requests: 1\r\nuser-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36\r\ndnt: 1\r\nreferer: http://localhost:3000/\r\naccept-encoding: gzip, deflate, br\r\naccept-language: pt-BR,pt;q=0.9,en-XA;q=0.8,en;q=0.7,en-US;q=0.6\r\nHost: localhost\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Agent],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path: '//hello-world?',
        _ended: false,
        res: null,
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Circular],
        [Symbol(isCorked)]: false,
        [Symbol(outHeadersKey)]: [Object] },
     _currentUrl: 'http://hello-world?' },
  response: undefined,
  statusCode: 500,
  name: 'NuxtServerError' }

 ERROR

  Error: connect ECONNREFUSED 127.0.0.1:80

  - net.js:1174 TCPConnectWrap.afterConnect [as oncomplete]
    net.js:1174:14
```

I think that 'path bug' is still unsolved... `path: '//hello-world?',` double slash isn't disappeared.

**Comment by peXed** [comment]
Looks like the port is not correct.
There must be an issue with the root url, too. I guess it gets not set?
But that has nothing to do with my changes.

**Comment by derevandal** [comment]
@peXed I tried again and I got 404 too.

screenshot_10
screenshot_9

I tested with axios 4.5.2 and 5.3.1... And I config URLs too.

Did you test in your pc?

**Comment by peXed** [comment]
I guess there is another issue in the current code. My changes will simply fix the issue with the path not getting correctly put together on Windows (and probably other OSs).
On my machine, I never got it to run correctly and unfortunately I have no time to look into the issue further.

**Comment by derevandal** [comment]
I understand you, but i got these errors only in your fork :S
I'll will reproduce your commits in another fork to test it

**Comment by cesasol** [comment]
This will be worked in the developement branch. But needs testing since a lot has changed

**Pull request closed without merging**
