### PR TITLE
Nuxt 1.0 [WIP]

### PR DESCRIPTION
**Pull request by cesasol**
Upgrading to the first stable release.

- [x] Dev Mode
- []  Universal Mode
- [] Static Mode

### CODE REVIEW

**Comment by cesasol** [comment]
Currently only dev works without errors, my first priority is the generate function as is the one that does not work in the current version.

**Comment by alidcastano** [comment]
Hi @cesasol Thanks for taking a lead on this. Let me know if you have any questions and I'll also take some time in the coming day to look into this & merge the upgrade

**Comment by ptibbetts** [comment]
Hey @cesasol, how is this going? 

Your changes work great in dev mode but I could not work out why the generate command is not creating the dynamic routes.

**Comment by cesasol** [comment]
@ptibbetts Unfortunately I have not had much time to devote to this, in fact I have 4 projects in production frozen to the last rc for it. I hope this week I have the time to finish this. And yes, my priority is the "generate" command.

**Comment by dimitrieh** [comment]
@cesasol @alidcastano it would be great to see this resolved ;) nuxtent is the only valid option I have found so far that provides decent content/blog functionality to your nuxt website 😉 

Nuxt is currently at 1.4 and it seems a lot of the issues currently in the issue tracker would be resolved by this pull request

**Comment by mootari** [comment]
@dimitrieh Think you could compile a list of issues that you think are directly caused by compatibility problems and add them here? I imagine that would be a great starting point for anyone else wanting to chime in.

**Comment by dimitrieh** [comment]
@mootari to my understanding the issues mentioned below would all benefit from getting this plugin working again with the newest version of nuxt 😉 

- https://github.com/nuxt-community/nuxtent-module/issues/133
- https://github.com/nuxt-community/nuxtent-module/issues/137
- https://github.com/nuxt-community/nuxtent-module/issues/140

**Comment by mootari** [comment]
Also referencing #127 because op mentions that he cannot create a build of the module.

**Comment by joostdecock** [comment]
I really want this module to work with the latest Nuxt, so I started digging around for option, and stumbled upon [this fork](https://github.com/apmontgomery/nuxtent-module) by @apmontgomery

I've added it to a fresh Nuxt setup, using the config from the nuxtent-template as an example, and it does seem to do the trick.

I'm not knowledgeable enough to asses whether it covers all bases, but it seems like this project could benefit from pulling in those changes. Thoughts?

**Comment by derevandal** [comment]
@alidcastano could u create a branch here to centralize v1.0.0 upgrade?

I found two forks and this hinders the collaboration of others.

https://github.com/dinamomx/nuxtent-module/tree/feature/nuxt-1.0
https://github.com/apmontgomery/nuxtent-module

@dimitrieh where do u find new hook system documentation?

Thanks all.

**Comment by apmontgomery** [comment]
I would be happy to help with this, but would need some support as I don't completely understand how nuxtent is built from source.   I looked at nuxt source code to understand the hooks system.  I don't believe there is documentation yet.  (or at least there wasn't when I looked)

**Comment by dimitrieh** [comment]
@derevandal I want to repeat here what I said at https://github.com/nuxt-community/nuxtent-module/pull/135#issuecomment-373857427 

> I am afraid I don't happen to have the expertise to solve this myself. Hoping someone else is up to the challenge!

So to answer your question: I don't know 😉 I am not the one to ask these questions to! (mostly UX Designer here)

**Comment by joostdecock** [comment]
I would like to help, but it's above my skillset. However, here's what I can do:

 - I've created [a fork that has all the lastest changes of this PR](https://github.com/joostdecock/nuxtent-module)
 - I've created [a minimal demo site that has everything setup to recreate the issue](https://github.com/joostdecock/nuxtent-example)
 - If you are somebody who can do this, but you have too much on your plate already, I am willing to pay 250USD to influence your priorities

I am not a developer, and I don't know if 250 is good enough to get people to look into this, but it's the best I can do. I need to make a call about whether I'm going to wait for this, or look into other solutions, so my offer is only relevant if you can do it fast(ish). 

Please forgive me if this is inappropriate, but the way I see it, everybody benefits if this gets done.

**Comment by alidcastano** [comment]
@joostdecock 

This isn't inappropriate at all. Thank you for doing what you can to get this moving.

I usually wouldn't mind devoting time to OSS (hence why I created Nuxtent) but my interests switched and my hands have been tied with [studbits.com](https://studbits.com/). So I haven't had the time or attention to devote to Nuxtent.

But I def want to see Nuxtent upgraded to 1.0. I don't have time this week to work on it, but can maybe take time this weekend. Would that work?

P.S. Anyone who's interested in contributing to Nuxtent, please join this [slack channel](https://join.slack.com/t/nuxtent/shared_invite/enQtMjQ1MzI4MzgxNzI5LTcwOTlkYTczNTMzMGU1YjYyYjlkNzNjNDc3MjQ3YTdmMjc0ZThkZjM1ZWY4ZjhiZjc1MDIwYjJmMjAxODlhMzU).  Feel free to DM directly if you have any specific questions about the code

**Comment by joostdecock** [comment]
Thanks :)

I want to use it for an open source project myself, and yes, I'm a noob 😂

I have time of from work this and next week so it's a perfect time for me to get some work in on my hobby project. That is why I'm so impatient (I know, I should have planned this better)

So the sooner I can get it the better. Which is why I'm very publicly offering this bounty. If it's not fixed by this weekend, then by all means go ahead. And if it is, that better for me, and less work for you :)

**Comment by alidcastano** [comment]
Sounds good! @medfreeman might also be interested, so I'll add him here

**Comment by joostdecock** [comment]
Quick bounty-hunter update:

To the best of my knowledge, the people who are interested in fixing this are:

 - @icarito who plans a solution *asap* [link](https://github.com/joostdecock/nuxtent-example/pull/1)
 - @cesasol who told me he'll try to come up with a beta fix *by the weekend*
 - @alidcastano who mentioned he might have some time for this *during the weekend*

I to want to do (part of) this work, please talk to each other to avoid double work.

**Comment by callumflack** [comment]
Happy to see this progressing! I'm grateful to @alidcastano 's work here because I think managing content on content-driven sites is all about markdown, and Nuxtent means I can make websites this way _with Nuxt_ and al it's benefits. I know @alidcastano is really busy, so it's cool to see there's a bunch of people who rate Nuxtent as highly as I do.

**Comment by joostdecock** [comment]
Hi guys,

Would you be so kind to check out his repository: https://github.com/joostdecock/nuxtent-example

It's a nuxtent site in which I had replicated this problem, and it seems to be resolved now.  
I could use some help verifying this solution. Just follow the steps in the README to setup..

Tx

**Comment by icarito** [comment]
Hey @joostdecock I'm glad you could move further yourself! I tried your solution and found the files generated, but the `index.html` in `dist/` doesn't seem to link to the generated files instead it tries to use the API. Let me know if you see the same issue and still can use help.

Cool project you got by the way (sewing with free software). I hope you succeed.

**Comment by joostdecock** [comment]
@icarito sorry, I'm just excited that we're making progress ;)

Yes you are right, we're not out of the woods yet. While the files are generated now (I also added the logoc to generate the dynamic routes) the navigation is still broken. Each page works as an entry point, but the SPA nagivation is not functioning as expected.

So yes, help is still very much needed ;)  I'll update my earlier comment to make that clear

And thanks, @freesewing is my pet project, and the reason why I'm trying to get this to work. I want to port its website from Jekyll to Nuxt.

**Comment by icarito** [comment]
@joostdecock indeed it looks like server-side rendering is broken except in dev mode - it works with `yarn dev` but try `yarn start` and it will fail just like the generated version - Debugging this should hopefully fix both.

**Comment by joostdecock** [comment]
Heads-up: It seems this is now resolved in this fork: https://github.com/joostdecock/nuxtent-module

It works both with `yarn build` + `yarn start` as well as with `yarn generate`. Just take care to set your `browserBaseURL` correctly.

A working example config is in https://github.com/joostdecock/nuxtent-example

@alidcastano If you could perhaps verify this, I can submit a PR if you'd like.

I'm sorry but I'm not enough of a got wizard to path this PR :(

**Comment by derevandal** [comment]
@joostdecock could u send a PR in this repo?
it will better if your fork pass in build test ;P

**Comment by joostdecock** [comment]
@derevandal [done](https://github.com/nuxt-community/nuxtent-module/pull/146) :)

**Comment by derevandal** [comment]
@alidcastano please, close this pr because of #146

**Pull request closed without merging**
